### ISSUE TITLE
the server address in front end is hard coded

### ISSUE THREAD

**Issue by zhangtemplar** [rahuljoshi44/GraphVega#11]
The front end assumes the server address is localhost:8000, this is not valid if it is not deployed locally.

**Comment by Rohan2002** [comment]
It's hardcoded because we won't be deploying this on the cloud for a while due to several third-party license agreements. However, if you prefer a different port mapping for the server API call, then you could make a port environmental variable and use that in the API calls.

Thanks,
-Rohan

**Comment by rahuljoshi44** [comment]
Yes, what @Rohan2002 said is correct.

**Comment by zhangtemplar** [comment]
I create #14 to address this issue.
