### ISSUE TITLE
Exact search for a company with only 1 return result 

### ISSUE THREAD

**Issue by rcouch00** [rahuljoshi44/GraphVega#2]
when res.data.securities.security does not return an array, but instead a single item, the UI crashes.

**Comment by rcouch00** [comment]
To reproduce

paste this into the search box "Walmart Inc"  without quotes

expected in dropdown:
- Walmart Inc (WMT)

actual:
- No options

**Comment by rahuljoshi44** [comment]
Thanks for letting me know, I will look into this soon.

**Comment by rahuljoshi44** [comment]
Saw your PR and merged it, thanks!

**Comment by rcouch00** [comment]
fixed with [PR]https://github.com/rahuljoshi44/GraphVega/commit/50780d8f73c87b31eee6fbeca963e2f6c1e24776
