### ISSUE TITLE
Bug with implied volatility slider?

### ISSUE THREAD

**Issue by samgoodrich1** [rahuljoshi44/GraphVega#7]
The default volatility values are not based in reality, and when I try to adjust them, the plot completely changes and doesn't recover until I swap tabs between option chain and analysis again, whereupon I get the extreme IV. Thanks BTW. I was thinking of making something myself very similar to help visualize what's happening over time. 
![image](https://user-images.githubusercontent.com/20916857/108036218-cc91bc00-6fec-11eb-84e7-47688e117e17.png)

**Comment by rahuljoshi44** [comment]
Hey Sam,
Can you please include a screenshot of the options that you added with which this bug is occurring? 
Thanks

**Comment by samgoodrich1** [comment]
It happens for all options for all stocks. (Screenshot of MSFT below)

I am running on Windows 10, using the web server, not Docker. I think the console output might offer a clue as to what's happening:

[client] Starting the development server...
[client]
[client] Compiled with warnings.
[client]
[client] src\components\analysis\lineChart.jsx
[client]   Line 10:3:  'ResponsiveContainer' is defined but never used  no-unused-vars
[client]
[client] src\components\analysis\positions.jsx
[client]   Line 71:52:  Expected '!==' and instead saw '!='  eqeqeq
[client]
[client] src\components\chain\editLayoutModal.jsx
[client]   Line 1:17:  'Component' is defined but never used  no-unused-vars
[client]
[client] src\components\chain\option.jsx
[client]   Line 38:9:    'setAlign' is assigned a value but never used       no-unused-vars
[client]   Line 50:9:    'setBackground' is assigned a value but never used  no-unused-vars
[client]   Line 60:48:   Expected '===' and instead saw '=='                 eqeqeq
[client]   Line 65:55:   Expected '===' and instead saw '=='                 eqeqeq
[client]   Line 228:31:  Expected '===' and instead saw '=='                 eqeqeq
[client]
[client] src\components\chain\optionChain.jsx
[client]   Line 78:7:  'options' is assigned a value but never used  no-unused-vars
[client]
[client] src\components\main.jsx
[client]   Line 85:14:  Expected '!==' and instead saw '!='  eqeqeq
[client]
[client] src\index.js
[client]   Line 6:8:  'Bootstrap' is defined but never used  no-unused-vars
[client]
[client] src\utils\bsm.js
[client]   Line 48:15:  Expected '!==' and instead saw '!='  eqeqeq
[client]
[client] src\utils\date.js
[client]   Line 1:7:  'parseDate' is assigned a value but never used  no-unused-vars
![image](https://user-images.githubusercontent.com/20916857/108100630-07224580-703b-11eb-8658-9057c975784c.png)

**Comment by rahuljoshi44** [comment]
Hi Sam,
I just checked on the platform with the same positions you posted and the same issue does not occur for me.
![graphvega-no-issue](https://user-images.githubusercontent.com/55931587/108106645-39906a80-705c-11eb-8ff9-d94364087efc.png)
I am not sure what is causing this on your machine. Maybe try using git pull to pull the latest changes in case something was overwritten accidentally?

**Comment by samgoodrich1** [comment]
Strange. I pulled the latest master and tried again and it's still doing it. Here's what it looks like when I adjust the slider:

![image](https://user-images.githubusercontent.com/20916857/108110350-fa581e80-7047-11eb-83d0-208e2815dce9.png)

I can try the Docker route to see if I get the same issue there.

**Comment by rahuljoshi44** [comment]
Sam,
I just released a new version of GraphVega (adding IV skew analysis). The volatility slider was working fine on it as well. Please try that one out to see if the issue persists.

**Comment by samgoodrich1** [comment]
I am still getting the same 1.26E31 implied volatility. 

I am seeing several warnings with "npm install" about requiring peers above a certain version number and needing to install peer dependencies myself. Could it be related? I know replicating your environment on someone else's machine can be very difficult.

**Comment by rahuljoshi44** [comment]
Hi Sam,
Run npm install again, and it should install all the dependencies. Honestly, the volatility issue is unfortunate, since it doesn't seem to be occurring on other's systems.

**Comment by samgoodrich1** [comment]
Interesting. It appears to be an issue with Firefox. When I use Chrome it works fine.

**Comment by samgoodrich1** [comment]
I'm just gonna close this with the caveat that one is required to use Chrome, or at least avoid Firefox. Works great with Chrome.
